[licenses]
version = 2  # Opt into new behavior
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Unlicense"
]

confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[advisories]
version = 2

[graph]
all-features = false
no-default-features = false
