[licenses]
version = 2  # Opt into new behavior
default = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Unlicense"
]

# We keep these default values from the new behavior
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.8
